apiVersion: apps/v1
kind: Deployment
metadata:
  name: notes-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notes-api
  template:
    metadata:
      labels:
        app: notes-api
    spec:
      containers:
        - name: api
          image: iamravi1/notes-app-api:1.0
          ports:
            - containerPort: 3000
          env:
            - name: DB_URL
              value: mongodb://db/notes
---
apiVersion: v1
kind: Service
metadata:
  name: notes-api
spec:
  selector:
    app: notes-api
  ports:
    - name: http
      port: 5000
      targetPort: 3000
  type: NodePort
